# Generated by Django 5.2.5 on 2025-11-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_question_text_question_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
