# Generated by Django 5.2.5 on 2025-11-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_question_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.subject",
            ),
        ),
    ]
