# Generated by Django 5.2.5 on 2025-11-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_question_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="questions",
            field=models.ManyToManyField(blank=True, to="core.question"),
        ),
    ]
