# Generated by Django 5.2.5 on 2025-11-05 22:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_assignment_questions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="questions",
        ),
        migrations.AddField(
            model_name="assignment",
            name="question",
            field=models.CharField(blank=True, verbose_name=core.models.Question),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(max_length=100),
        ),
    ]
