# Generated by Django 5.2.5 on 2025-11-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_assignment_questions_assignment_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="question",
        ),
        migrations.AddField(
            model_name="assignment",
            name="questions",
            field=models.ManyToManyField(blank=True, to="core.question"),
        ),
    ]
