# Generated by Django 5.2.5 on 2025-11-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_assignment_question_assignment_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="answers_json",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
