# Generated by Django 5.2.5 on 2025-11-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_submission_answers_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="answers_json",
        ),
    ]
