# Generated by Django 5.2.5 on 2025-11-19 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_submission_answers_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students assigned to this assignment",
                related_name="assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
